// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ageebSoft.RoomService.Data;

namespace ageebSoft.RoomService.Migrations
{
    [DbContext(typeof(MyDB))]
    [Migration("20200302124736_A2020_03_02")]
    partial class A2020_03_02
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("ageebSoft.RoomService.Models.Cust", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<DateTime?>("Date1");

                    b.Property<DateTime?>("Date_Add");

                    b.Property<DateTime?>("Date_Edit");

                    b.Property<string>("Name");

                    b.Property<string>("Note");

                    b.Property<string>("Tel");

                    b.Property<string>("User_Add");

                    b.Property<string>("User_Edit");

                    b.HasKey("Id");

                    b.ToTable("Custs");
                });

            modelBuilder.Entity("ageebSoft.RoomService.Models.Rooms", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CustId");

                    b.Property<DateTime?>("Date1");

                    b.Property<DateTime?>("Date_Add");

                    b.Property<DateTime?>("Date_Edit");

                    b.Property<string>("DoorKey");

                    b.Property<string>("Level");

                    b.Property<string>("Note");

                    b.Property<string>("RoomNo");

                    b.Property<string>("User_Add");

                    b.Property<string>("User_Edit");

                    b.HasKey("Id");

                    b.HasIndex("CustId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("ageebSoft.RoomService.Models.RoomsMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CustId");

                    b.Property<DateTime?>("Date1");

                    b.Property<DateTime?>("Date_Add");

                    b.Property<DateTime?>("Date_Edit");

                    b.Property<string>("Note");

                    b.Property<Guid?>("RoomId");

                    b.Property<Guid?>("RoomsId");

                    b.Property<string>("User_Add");

                    b.Property<string>("User_Edit");

                    b.HasKey("Id");

                    b.HasIndex("CustId");

                    b.HasIndex("RoomsId");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("ageebSoft.RoomService.Models.Rooms", b =>
                {
                    b.HasOne("ageebSoft.RoomService.Models.Cust", "Cust")
                        .WithMany()
                        .HasForeignKey("CustId");
                });

            modelBuilder.Entity("ageebSoft.RoomService.Models.RoomsMovement", b =>
                {
                    b.HasOne("ageebSoft.RoomService.Models.Cust", "Cust")
                        .WithMany()
                        .HasForeignKey("CustId");

                    b.HasOne("ageebSoft.RoomService.Models.Rooms", "Rooms")
                        .WithMany()
                        .HasForeignKey("RoomsId");
                });
#pragma warning restore 612, 618
        }
    }
}
