// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ageebSoft.RoomService.Data;

namespace ageebSoft.RoomService.Migrations
{
    [DbContext(typeof(MyDB))]
    partial class MyDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("ageebSoft.RoomService.Models.Movement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CustName");

                    b.Property<DateTime?>("Date1");

                    b.Property<DateTime?>("Date_Add");

                    b.Property<DateTime?>("Date_Edit");

                    b.Property<string>("Note");

                    b.Property<Guid?>("RoomId");

                    b.Property<string>("User_Add");

                    b.Property<string>("User_Edit");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("ageebSoft.RoomService.Models.Rooms", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CustName");

                    b.Property<DateTime?>("Date1");

                    b.Property<DateTime?>("Date_Add");

                    b.Property<DateTime?>("Date_Edit");

                    b.Property<string>("DoorKey");

                    b.Property<string>("Level");

                    b.Property<string>("Note");

                    b.Property<string>("RoomNo");

                    b.Property<string>("User_Add");

                    b.Property<string>("User_Edit");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("ageebSoft.RoomService.Models.Movement", b =>
                {
                    b.HasOne("ageebSoft.RoomService.Models.Rooms", "Rooms")
                        .WithMany("Movements")
                        .HasForeignKey("RoomId");
                });
#pragma warning restore 612, 618
        }
    }
}
